src/main/java/org/jahia/modules/reports/action/ContentReportAction.java, src/main/java/org/jahia/modules/reports/bean/ReportContentMarkedForDeletion.java, src/main/resources/cgnt_contentReportsAdministration/html/contentReportsAdministration.jsp, src/main/resources/cgnt_contentReportsAdministration/html/contentReportsAdministration.markedForDeletion.jsp, src/main/resources/javascript/reports.js, src/main/resources/resources/content-reports.properties, src/main/resources/resources/content-reports_fr.properties
https://jira.jahia.org/browse/BACKLOG-11881
=> BACKLOG-11881 : Add view to show the contents marked for deletion

.gitignore, src/main/java/org/jahia/modules/reports/action/ContentReportAction.java, src/main/java/org/jahia/modules/reports/bean/ReportContentMarkedForDeletion.java, src/main/resources/cgnt_contentReportsAdministration/html/contentReportsAdministration.jsp, src/main/resources/cgnt_contentReportsAdministration/html/contentReportsAdministration.markedForDeletion.jsp, src/main/resources/javascript/reports.js, src/main/resources/resources/content-reports.properties, src/main/resources/resources/content-reports_fr.properties
https://jira.jahia.org/browse/PROJECT-XXX
=> Backlog 11886 add criteria to limit the result

src/main/java/org/jahia/modules/reports/bean/ReportContentMarkedForDeletion.java, src/main/resources/cgnt_contentReportsAdministration/html/contentReportsAdministration.markedForDeletion.jsp, src/main/resources/resources/content-reports.properties
https://jira.jahia.org/browse/BACKLOG-11937
=> BACKLOG-11937 : add column published to know the publication status

src/main/java/org/jahia/modules/reports/bean/ReportContentMarkedForDeletion.java
https://jira.jahia.org/browse/BACKLOG-11958
=> BACKLOG-11958 : count children nodes for just some node types

src/main/resources/cgnt_contentReportsAdministration/html/contentReportsAdministration.jsp, src/main/resources/javascript/reports.js
https://jira.jahia.org/browse/QA-10745
=> QA-10745 : retrieve ace and acl nodes for broken inheritance acl

src/main/resources/cgnt_contentReportsAdministration/html/contentReportsAdministration.jsp, src/main/resources/javascript/apps/jahia.json, src/main/resources/javascript/apps/register.js, src/main/resources/javascript/content-report-app.js, src/main/resources/javascript/locales/de.json, src/main/resources/javascript/locales/en.json, src/main/resources/javascript/locales/fr.json
https://jira.jahia.org/browse/PROJECT-XXX
=> BACKLOG-12272 : Added content reports in jcontent

src/main/resources/javascript/apps/register.js
https://jira.jahia.org/browse/PROJECT-XXX
=> BACKLOG-12272: Updated label/icon/ordering

src/main/resources/javascript/apps/register.js
https://jira.jahia.org/browse/PROJECT-XXX
=> BACKLOG-12877: Fixed links

src/main/resources/javascript/apps/register.js
https://jira.jahia.org/browse/BACKLOG-12942
Just fixed the priority for the position in the additional accordion
=> BACKLOG-12942: updated position in the additional accordion

src/main/resources/javascript/locales/de.json, src/main/resources/javascript/locales/en.json, src/main/resources/javascript/locales/fr.json
https://jira.jahia.org/browse/BACKLOG-12941
Fixed labels + added German labels
=> BACKLOG-12941: Fixed labels in site settings

src/main/resources/javascript/apps/register.js
https://jira.jahia.org/browse/BACKLOG-13102
Just added the icon for the content report module
=> BACKLOG-13102: added icon for content reports entry in nav

src/main/resources/javascript/locales/de.json
https://jira.jahia.org/browse/BACKLOG-12941
Add a missing German translation, seen during the tests
=> [BACKLOG-12941] Add a missing german translation

pom.xml, src/main/resources/META-INF/spring/content-reports.xml
https://jira.jahia.org/browse/BACKLOG-14145
=> BACKLOG-14145: Allow get methods

pom.xml
https://jira.jahia.org/browse/BACKLOG-8105
=> [BACKLOG-8105] Update module signature

src/main/java/org/jahia/modules/reports/bean/ReportByExpiredContent.java, src/main/java/org/jahia/modules/reports/bean/ReportLiveContents.java, src/main/java/org/jahia/modules/reports/service/ExpiredConditionService.java, src/main/java/org/jahia/modules/reports/service/LiveConditionService.java
https://jira.jahia.org/browse/BACKLOG-14951
* Remove duplicate entries between the Live content with visibility condition reports and the expired / future reports
* Content found in the expired / future content reports should not show in the live content with visibility condition reports
=> Fix live visibility report. Remove duplicate entries

src/main/java/org/jahia/modules/reports/bean/ReportByExpiredContent.java, src/main/java/org/jahia/modules/reports/bean/ReportByFutureContent.java, src/main/java/org/jahia/modules/reports/bean/ReportLiveContents.java, src/main/java/org/jahia/modules/reports/service/ExpiredConditionService.java
https://jira.jahia.org/browse/BACKLOG-14967
Fix the incorrect number of entries
=> BACKLOG-14967: Number of entries is false when a content has an expired + visible condition

src/main/java/org/jahia/modules/reports/bean/ReportByExpiredContent.java, src/main/java/org/jahia/modules/reports/bean/ReportByFutureContent.java, src/main/java/org/jahia/modules/reports/bean/ReportLiveContents.java
https://jira.jahia.org/browse/BACKLOG-14967
Fix number of entry found at the bottom of the table
=> BACKLOG-14967: Fix num of entry at bottom of the table

src/main/resources/cgnt_contentReportsAdministration/html/contentReportsAdministration.jsp
https://jira.jahia.org/browse/QA-13268
This is only fixing jcontent links ( the ones that were broken ), links to page composer are actually generated by the core and cannot be fixed here.
=> QA-13268: Fixed jcontent link

pom.xml
=> Fixed version of the module in preparation for a future release

.github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, .github/workflows/on-release.yml, pom.xml
https://jira.jahia.org/browse/TECH-1275
Add cyclonedx-maven-plugin and create/upload SBOMs on merge and release
=> TECH-1275: Add SBOM creation

pom.xml, src/main/import/repository.xml
https://jira.jahia.org/browse/BACKLOG-22406
=> BACKLOG-22406: Cleanup dependencies
